version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Correct indentation here
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=dockerdb
      - DB_USER=dockeruser
      - DB_PASS=dockerpass
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: dockerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

