version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: dockerdb
      DB_USER: dockeruser
      DB_PASS: dockerpass
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: dockerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
